# Form implementation generated from reading ui file 'ui_aipdf.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AIPDF(object):
    def setupUi(self, AIPDF):
        AIPDF.setObjectName("AIPDF")
        AIPDF.resize(600, 400)
        AIPDF.setMaximumSize(QtCore.QSize(600, 400))
        self.centralwidget = QtWidgets.QWidget(parent=AIPDF)
        self.centralwidget.setObjectName("centralwidget")
        self.answer_browser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.answer_browser.setEnabled(True)
        self.answer_browser.setGeometry(QtCore.QRect(10, 90, 579, 269))
        self.answer_browser.setObjectName("answer_browser")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 364, 579, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.openai_key_edit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.openai_key_edit.setObjectName("openai_key_edit")
        self.horizontalLayout_3.addWidget(self.openai_key_edit)
        self.save_openai_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.save_openai_btn.setMinimumSize(QtCore.QSize(120, 0))
        self.save_openai_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        self.save_openai_btn.setCheckable(True)
        self.save_openai_btn.setObjectName("save_openai_btn")
        self.horizontalLayout_3.addWidget(self.save_openai_btn)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 8, 579, 28))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.open_pdf_btn = QtWidgets.QPushButton(parent=self.widget)
        self.open_pdf_btn.setMinimumSize(QtCore.QSize(120, 0))
        self.open_pdf_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        self.open_pdf_btn.setObjectName("open_pdf_btn")
        self.horizontalLayout.addWidget(self.open_pdf_btn)
        self.pdf_path_label = QtWidgets.QLabel(parent=self.widget)
        self.pdf_path_label.setText("")
        self.pdf_path_label.setObjectName("pdf_path_label")
        self.horizontalLayout.addWidget(self.pdf_path_label)
        self.widget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(10, 47, 579, 33))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.question_input = QtWidgets.QLineEdit(parent=self.widget1)
        self.question_input.setObjectName("question_input")
        self.horizontalLayout_2.addWidget(self.question_input)
        self.question_btn = QtWidgets.QPushButton(parent=self.widget1)
        self.question_btn.setMinimumSize(QtCore.QSize(120, 0))
        self.question_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        self.question_btn.setObjectName("question_btn")
        self.horizontalLayout_2.addWidget(self.question_btn)
        AIPDF.setCentralWidget(self.centralwidget)

        self.retranslateUi(AIPDF)
        QtCore.QMetaObject.connectSlotsByName(AIPDF)

    def retranslateUi(self, AIPDF):
        _translate = QtCore.QCoreApplication.translate
        AIPDF.setWindowTitle(_translate("AIPDF", "AI PDF"))
        self.save_openai_btn.setText(_translate("AIPDF", "设置OPENAI_KEY"))
        self.open_pdf_btn.setText(_translate("AIPDF", "打开PDF"))
        self.question_btn.setText(_translate("AIPDF", "提问"))
